name: Create New Release

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'true'
          fetch-depth: 0
      
      - name: Use Xcode 26.2
        run: |
          sudo xcode-select -s /Applications/Xcode_26.2.app/Contents/Developer

      - name: Compile Feather
        run: | 
          agvtool new-version -all $(git rev-parse HEAD)
          make
          mkdir -p upload
          # ئەم دێرەی خوارەوە دڵنیا دەبێتەوە کە فایلەکان دەچنە ناو فۆڵدەری upload
          find . -name "*.ipa" -exec mv {} upload/ \;

      - name: Get Version
        id: get_version
        run: |
          # گەڕان بەدوای فایلی Info.plist بۆ دۆزینەوەی ڤێرژن
          VERSION_PATH=$(find . -name "Info.plist" | grep "Payload" | head -n 1)
          VERSION=$(/usr/libexec/PlistBuddy -c "Print CFBundleShortVersionString" "$VERSION_PATH")
          echo "VERSION=${VERSION}" >> $GITHUB_ENV

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          name: Feather v${{ env.VERSION }}
          tag_name: v${{ env.VERSION }}
          files: |
            upload/*.ipa
          generate_release_notes: true
          fail_on_unmatched_files: false
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
