Name: Create New Release

on:
  workflow_dispatch:

# ١. زیادکردنی مۆڵەتەکان لێرە زۆر گرنگە بۆ ئەوەی ڕێگەت پێ بدات ریلیز دروست بکەیت
permissions:
  contents: write

jobs:
  build:
    runs-on: macos-26 # دڵنیابە ئەم ڤێرژنەی ماک لای گیتھەب بەردەستە (بەزۆری macos-14 یان macos-latest بەکاردێت)
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'true'
          fetch-depth: 0 # بۆ ئەوەی agvtool کێشەی نەبێت لەگەڵ گیت
      
      - name: Use Xcode 26.2
        run: |
          sudo xcode-select -s /Applications/Xcode_26.2.app/Contents/Developer

      - name: Compile Feather
        run: | 
          agvtool new-version -all $(git rev-parse HEAD)
          make
          mkdir upload
          mv packages/* upload/

      - name: Get Version
        id: get_version
        run: |
          # دڵنیابە ناونیشانی Payload دروستە، ئەگەر لە ناو فۆڵدەرێکی تر بوو بیگۆڕە
          VERSION=$(/usr/libexec/PlistBuddy -c "Print CFBundleShortVersionString" Payload/*.app/Info.plist)
          echo "VERSION=${VERSION}" >> $GITHUB_ENV

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          name: Feather v${{ env.VERSION }}
          tag_name: v${{ env.VERSION }}
          files: |
            upload/*.ipa
          generate_release_notes: true
          fail_on_unmatched_files: true
          draft: true
        env:
          # ٢. لێرەدا دەبێت secrets.GITHUB_TOKEN بەکاربێنیت نەک env.GITHUB_TOKEN
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
